version: "3.9"
services:
  dev:
    container_name: musicoteca-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "5173"
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - .:/musicoteca
      - /musicoteca/node_modules
volumes:
  node_modules: