#
name: Generate medias from Musescore files

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:

jobs:
  generate-medias:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/soprodecarnaval/musicoteca:main
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate media generator file
        shell: bash
        run: |
          find public/collection/ -type f -name "*.mscz" | jq -R -s 'split("\n") | map(select(.!="") | sub(".mscz";"") | {"in":"\(.).mscz", "out": [[ "\(.)_",".svg"],[ "\(.)_",".midi"],"\(.).midi","\(.).metajson"]})' > media-generation.json
          head media-generation.json
          alias
          xvfb-run /squashfs-root/AppRun -j media-generation.json
  # index-files:
